from pathlib import Path

CONF = Path("/mnt/pfs/devs/pn5wp/shishuqing/partnr-planner/habitat_llm/conf/instruct")
NOTE = (
    "# The arm's own instruct with a memory slot, and nothing else changed.\n"
    "#\n"
    "# `LLMPlanner` only consults `self.rag` when the prompt actually contains\n"
    "# `{rag_examples}`, and the few-shot decentralized instructs do not: an arm can set\n"
    "# `enable_rag: True`, build the retriever, and never once put a retrieved thing in\n"
    "# front of the model. This file is the stock instruct with that slot inserted in the\n"
    "# position `instruct/zero_shot_prompt.yaml` uses -- after the examples, immediately\n"
    "# before the task -- so that every prompt-shaped memory arm is compared on what it\n"
    "# retrieved rather than on whether the retrieval was wired up.\n"
    "# Generated by scripts/partnr_make_memory_instructs.py; do not edit by hand.\n"
)

for role in ("robot", "human"):
    source = CONF / f"few_shot_decentralized_partial_{role}_spatialobjstates_instruct.yaml"
    target = CONF / f"few_shot_decentralized_partial_{role}_spatialobjstates_memory_instruct.yaml"
    lines = source.read_text().splitlines(keepends=True)
    anchor = next(i for i, line in enumerate(lines) if line.strip() == "Task: {input}")
    # The `{user_tag}` immediately above the task is where zero_shot_prompt puts it.
    insert = anchor - 1
    assert lines[insert].strip() == "{user_tag}", lines[insert]
    indent = lines[insert][: len(lines[insert]) - len(lines[insert].lstrip())]
    lines.insert(insert, f"{indent}{{rag_examples}}\n")
    target.write_text(NOTE + "".join(lines))
    print(f"wrote {target.name}  (slot at line {insert + 1})")
