#!/usr/bin/env python3
"""Write results/paper_viki_iclr2027/README.md for the VIKI-L2 ICLR 2027 supplement.

Procedure and deviations are prose; everything that is a count, a status, a hash or a list of
cells is read from cells.json, induction_ledger.json, run_manifest.json and the library
directories at the time this runs. No success rate is written here: those live in the
summary CSVs and paper_viki_results.md produced by scripts/export_paper_viki_results.py.

Run on the remote, after the exporter:
    /root/venvs/partnr/bin/python scripts/write_paper_viki_readme.py
"""
from __future__ import annotations

import collections
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PAPER = ROOT / "results/paper_viki_iclr2027"


def load(name):
    path = PAPER / name
    return json.loads(path.read_text()) if path.is_file() else None


def sha(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest() if path.is_file() else "absent"


def library_rows(condition_dir: Path):
    rows = []
    for f in sorted(condition_dir.glob("memory_*.json")):
        try:
            data = json.loads(f.read_text())
            ops = data.get("operators", data.get("layer1", {}).get("operators") if isinstance(data.get("layer1"), dict) else None)
            n = len(ops) if isinstance(ops, list) else "?"
        except Exception:
            n = "?"
        rows.append((f.name, n, sha(f)[:16]))
    return rows


def main() -> int:
    cells = load("cells.json")["cells"]
    ledger = load("induction_ledger.json") or {}
    manifest = load("run_manifest.json") or {}
    out = []
    w = out.append

    w("# VIKI-L2 supplementary results for ICLR 2027\n")
    w("Generated by `scripts/write_paper_viki_readme.py`. Counts, statuses, hashes and cell lists below are read "
      "from `cells.json`, `induction_ledger.json`, `run_manifest.json` and the library files when this README is "
      "written. Success rates are **not** in this file: see `figure2_tom_summary.csv`, `rq2_summary.csv`, "
      "`rq3_summary.csv`, `paired_tests.csv` and `paper_viki_results.md`, all produced from the row files by "
      "`scripts/export_paper_viki_results.py`.\n")
    if manifest.get("git"):
        w("Exporter git state: `%s`\n" % json.dumps(manifest["git"])[:300])

    # ------------------------------------------------------------------ status
    w("## Status\n")
    by_exp = collections.defaultdict(lambda: collections.Counter())
    for c in cells:
        by_exp[c["experiment"]]["total"] += 1
        by_exp[c["experiment"]][c.get("status", "?")] += 1
        by_exp[c["experiment"]]["reuse:" + str(c.get("reuse"))] += 1
    w("| experiment | cells | available | missing | reused | newly executed |")
    w("|---|---|---|---|---|---|")
    for exp in ("figure2", "rq2", "rq3"):
        k = by_exp[exp]
        w("| %s | %d | %d | %d | %d | %d |" % (exp, k["total"], k["available"], k["missing"],
                                             k["reuse:reused"], k["reuse:newly_executed"]))
    w("\nAvailability here is the registry status; the exporter additionally checks expected_n, duplicate "
      "example_id and manifest equality and publishes no aggregate for a cell that fails (column `complete` in the "
      "summary CSVs).\n")

    w("### Incomplete or missing cells\n")
    missing = [c for c in cells if c.get("status") != "available"]
    if missing:
        for c in missing:
            w("- `%s` -- %s" % (c["cell_id"], c.get("notes", "")))
    else:
        w("None: every registered cell has a complete row file. Runs that were interrupted and resumed are listed "
          "under *Run history* below.")
    w("")

    # ------------------------------------------------------------------ models
    w("## Models\n")
    w("The task text names the columns Qwen2.5-72B / Qwen3-8B / Qwen2.5-7B-Instruct. The row-level artifacts behind "
      "the current main results were produced by vision-language checkpoints, and every export records the real one "
      "(`model_display_name`) next to the task's label (`task_display_name`). No Qwen3-8B or text-only Qwen2.5-7B "
      "VIKI run exists in this repository, and the image-bearing splits cannot be run by text-only models; the "
      "decision (2026-09-14) was to keep the models the main results used and name them truthfully.\n")
    w("| task label | model actually used | served id |")
    w("|---|---|---|")
    w("| Qwen2.5-72B | Qwen/Qwen2.5-VL-72B-Instruct, revision 89c86200 | qwen2.5-vl-72b-amendment3-f2 |")
    w("| Qwen3-8B | Qwen/Qwen3-VL-30B-A3B-Instruct, revision 9c4b90e1 | qwen3-vl-30b |")
    w("| Qwen2.5-7B-Instruct | Qwen/Qwen2.5-VL-7B-Instruct | qwen2.5-vl-7b |\n")
    w("Serving for the newly executed cells (2026-09-14/15):\n")
    w("- 72B: the archived endpoint (192.168.32.40:8050) was unreachable, so the same revision was served on this box "
      "with `scripts/drivers/viki_serve_72b_local.sh` (vLLM 0.11.2 instead of the archived .venv-amendment3; TP=4; "
      "16k context; same multimodal and generation-config flags; `--max-num-seqs 64` instead of 16). First on GPUs "
      "1,2,3,5 at gpu-memory-utilization 0.48 (other users' jobs left too little memory for 0.70), then moved to "
      "GPUs 0,2,4,5 at 0.62 because GPU 1 was compute-contended; every job was stopped and resumed across the move "
      "(see *Run history*).")
    w("- 30B: TP=1 on one GPU (archived main results used TP=4). Tensor-parallel degree changes numerics slightly.")
    w("- 7B: TP=1, as archived.")
    w("- Temperature is 0 everywhere, but vLLM is not bit-deterministic at temperature 0 (two identical zero-shot "
      "runs agreed on few rows, and live re-asks differ between runs); small differences between reruns are expected.\n")

    # ------------------------------------------------------------------ scorer and splits
    w("## Scoring\n")
    w("- Ours and every RQ2/RQ3 condition: the archived answer (or the live re-ask) is executed by the simulator and a "
      "row succeeds iff `reason == \"SOLVED\"` (`our_method/skill_memory_v2/simulator.py`). The model's JSON is parsed "
      "by `scripts/viki_amendment11_goalparse.py::extract_json`.")
    w("- Figure-2 baselines and ToM: JSON-tolerant scorer `scripts/viki_report_matrix.py::tolerant` with parser "
      "`scripts/viki_amendment9_diag102.py::parse_plan`. The official strict scorer is not used.")
    w("- Scorer/parser source hashes are in `run_manifest.json`.\n")
    w("## Splits\n")
    w("| canonical_split | source name | rows | definition |")
    w("|---|---|---|---|")
    w("| id | id | 924 | `results/viki_memory_experiments/amendment8b/interactive_manifest.jsonl` over VIKI-L2 test.parquet |")
    w("| ood_single_family | heldout | 924 | the same 924 examples; each of the 8 test families is scored with a library "
      "induced without that family, then the 8 folds are concatenated (unique example_id, checked) |")
    w("| cg_image | imaged | 297 | `results/viki_memory_experiments/amendment10/recombination.imaged.parquet` |")
    w("| pure_text | text | 297 | `results/viki_memory_experiments/amendment10/recombination.text.parquet` |\n")
    w("Sibling-group held-out results exist in the repository but are not part of any table here.\n")
    w("OOD fold libraries are fresh unions of the other 13 per-family libraries (never a filter of the 14-family "
      "union). A fold run scores only its held-out family's rows; rows are scored independently, so this equals "
      "scoring all 924 and keeping that family.\n")

    # ------------------------------------------------------------------ figure 2
    w("## Figure 2 -- ToM arm\n")
    tom_prompt = ROOT / "prompts/viki_tom_prompt.txt"
    canon = ROOT / "prompts/viki_tom_canonical_template.txt"
    w("- No VIKI-L2 ToM arm existed on the current harness. The canonical instruction is "
      "`scripts/viki_amendment6.py::TOM_REASONING_TEMPLATE` (saved verbatim as `prompts/viki_tom_canonical_template.txt`, "
      "sha256 `%s`)." % sha(canon))
    w("- That template does not ask what the other robots have already done or which subgoal they pursue next. On "
      "2026-09-14 one adapter line was added (decision recorded in the task log): the step-1 partner actions are what "
      "the other robots have done; infer their next subgoal and give complementary actions. Final prompt "
      "`prompts/viki_tom_prompt.txt`, sha256 `%s`; every ToM row records `prompt_sha256`." % sha(tom_prompt))
    w("- The request is the zero-shot arm's own payload (same messages, image, model, temperature 0, max_tokens 2000, "
      "seed 20260829, think rule kept) plus the ToM text appended to the system message; `scripts/viki_tom_arm.py "
      "payload-diff` verified this on every row. No memory, trajectories, targets or other arms' outputs are used.")
    w("- Runner: `scripts/viki_tom_arm.py run`; drivers `scripts/drivers/viki_tom_cells.sh` (sequential) and "
      "`scripts/drivers/viki_tom_split.sh` (one split per endpoint replica). OOD is 8 fold runs merged by "
      "`viki_tom_arm.py merge-folds`, never copied from ID.")
    w("- Figure-2 method list: Ours, ToM, G-Memory, MEMENTO-style, Trajectory RAG, Zero-shot. Skill Memory v1 is "
      "scored by the exporter only to cross-check `baseline_comparison.json` and is excluded from every Figure-2 output.\n")

    # ------------------------------------------------------------------ RQ2
    w("## RQ2 -- induction and admission\n")
    conds = ledger.get("conditions", {})
    fields = ["exposed_training_episode_count", "exposed_trace_count", "family_count", "proposal_budget",
              "proposal_attempt_count", "returned_candidate_count", "format_valid_count", "type_valid_count",
              "execution_tested_count", "execution_passed_count", "deduplicated_skill_count", "library_sha256"]
    if conds:
        w("From `induction_ledger.json`:\n")
        w("| field | " + " | ".join(conds) + " |")
        w("|---|" + "---|" * len(conds))
        for f in fields:
            vals = []
            for name in conds:
                v = conds[name].get(f)
                if isinstance(v, dict):
                    v = json.dumps(v)[:40]
                vals.append(str(v)[:24] if f == "library_sha256" and v else str(v))
            w("| %s | %s |" % (f, " | ".join(vals)))
        w("")
    w("- **full**: the current v3 pipeline and library (`outputs/v3_memories/memory_all.json`). Its downstream cells "
      "are the existing v3 Ours rows, re-exported (reused).")
    w("- **no_execution_admission**: execution admission is inside the proposer loop (submit, execute, refusal fed "
      "back), so no separate pre-admission batch exists. Decision (2026-09-14): take every submission from full's own "
      "896 proposer transcripts (no resampling; each rejected submission appears twice in a transcript and is counted "
      "once), keep format/type/schema checks, skip execution admission and the support re-probe, then the same "
      "per-family assembly, union and 8 fold unions. `support` (unmeasured without execution) is set to the number "
      "of proposal cells that submitted the operator. Built by `scripts/viki_rq2_no_exec_admission.py`; candidates in "
      "`libraries/rq2/candidates_full_preadmission.jsonl`. These submissions were shaped by execution feedback during "
      "full's run.")
    w("- **no_trace**: the full budget re-run (round 1 = 784 cells, round 2 = 112 cells) with the same 72B proposer "
      "and `--no-traces` (`scripts/drivers/viki_rq2_no_trace.sh`). The proposer still receives execution feedback on "
      "each submission (which holdout episodes it works on, bound object names), as full does; only trajectories and "
      "trajectory-derived tools are removed. Round-2 targets use full's seeds/holdout/pool (checked equal) with "
      "no_trace's own round-one libraries. Without tools every reply is a submission, so the candidate count is far "
      "larger than full's while the number of distinct operators is small; the 896-cell budget is nominal, not 896 "
      "independent samples. Under `--no-traces` the rung omits the two-robot interface text in round 2, mirrored as is. "
      "The stale 56-cell no_trace run under `outputs/agentic_rung/v2_notrace/` is kept for reference only.")
    w("- Known exposure note for every condition: the induction tool `list_episodes` can list other families' "
      "induction-half episodes.\n")
    w("Library files:\n")
    for cond in ("full", "no_execution_admission", "no_trace"):
        d = PAPER / "libraries/rq2" / cond
        rows = library_rows(d)
        if rows:
            w("- `%s`: " % cond + ", ".join("%s (%s ops, %s)" % r for r in rows))
    w("")

    # ------------------------------------------------------------------ RQ3
    w("## RQ3 -- representation ablations\n")
    w("- Existing mechanism reused: runtime flags of `scripts/viki_eval_v2_intent_choice.py`.")
    w("- **no_grounding** (`--no-grounding`): bypasses Layer-3 vocabulary matching (object X must equal a scene asset "
      "name, place Y is used as written). The transformed library clears `layer3.assets` and `layer3.places`, but the "
      "flag also changes matching logic, so the flag is authoritative and the transformed file documents what is "
      "disabled (`libraries/rq3/transform_report.json`).")
    w("- **no_order** (`--no-order`): Layer-2 temporal constraints are emptied (not permuted; no seed). Transformed "
      "library clears `layer2.kept_patterns` and marks every rule unkept; equivalent to the flag by construction.")
    w("- Structural checks (same skill count, identical layer 1 so action order and multiset unchanged, grounding or "
      "ordering fields removed) pass for the 14-family library and all 8 fold libraries (`transform_report.json`).")
    w("- OOD: each fold library is transformed, then its fold is run, then the 8 folds are assembled.")
    w("- 72B id / cg_image / pure_text ablation rows are the existing v3 `v3_ablfull_*` files (2026-09-10, full v3 "
      "library; the rows carry no library hash, the library path is inferred from the driver invocation). 7B rows "
      "were re-run on 2026-09-14 and agree with the archived 7B ablfull files on success for every id row. The "
      "comp_cd half memory and every v2 ablation file are excluded.\n")
    for cond in ("no_grounding", "no_order"):
        rows = library_rows(PAPER / "libraries/rq3" / cond)
        if rows:
            w("- `%s`: " % cond + ", ".join("%s (%s ops, %s)" % r for r in rows))
    w("")

    # ------------------------------------------------------------------ reuse lists
    w("## Reused vs newly executed cells\n")
    for reuse in ("reused", "newly_executed"):
        ids = [c["cell_id"] for c in cells if c.get("reuse") == reuse]
        w("<details><summary>%s (%d)</summary>\n" % (reuse, len(ids)))
        for i in ids:
            w("- `%s`" % i)
        w("\n</details>\n")

    # ------------------------------------------------------------------ run history
    w("## Run history and incidents (2026-09-14/15)\n")
    w("- The first 72B launch failed at startup (free GPU memory 48 GiB < requested 0.70); relaunched at 0.48.")
    w("- 72B ToM `pure_text` was stopped once by its 20-minute stall guard while the endpoint was compute-starved; it "
      "resumed from its rows (resume only fills missing example_ids; duplicates are rejected by the exporter).")
    w("- 20:34: all 72B jobs and servers were stopped to move the 72B to less contended GPUs; ToM row files were "
      "checked for partial trailing lines (none) and every job resumed at 20:37.")
    w("- RQ2 no_trace: round 1 finished 784/784 at 02:45, then the round-2 targets step failed on a relative "
      "`--out` path (`ValueError` in `relative_to`). Fixed in the driver (commit ecb3196, absolute path; the targets "
      "script and full's targets are unchanged) and resumed at 10:14 from the targets stage; round-1 verdicts were "
      "not re-run.")
    w("- 30B no_trace downstream first ran while the 30B endpoint was down (it had been stopped to free a GPU); "
      "those attempts produced no rows and their run.json files were moved aside before the real 30B run.\n")

    # ------------------------------------------------------------------ rerun
    w("## How to rerun (remote, repo root)\n")
    w("```bash")
    w("# endpoints")
    w("GPUS=0,2,4,5 GPU_UTIL=0.62 setsid nohup bash scripts/drivers/viki_serve_72b_local.sh > /root/vllm-72b.log 2>&1 &")
    w("# Figure 2 ToM, one model, all splits (or viki_tom_split.sh with SPLITS=... BASE=...)")
    w("MODEL=7B bash scripts/drivers/viki_tom_cells.sh")
    w("# RQ2 libraries")
    w("python scripts/viki_rq2_no_exec_admission.py            # no_execution_admission")
    w("URL=http://127.0.0.1:8050/v1 R1_FAMILY_WORKERS=14 WORKERS=16 bash scripts/drivers/viki_rq2_no_trace.sh all")
    w("python scripts/viki_rq2_induction_ledger.py")
    w("# RQ3 transformed libraries")
    w("python scripts/viki_rq3_transform_library.py")
    w("# downstream cells (any experiment / condition / model / split)")
    w("EXPERIMENT=rq2 MODEL=72B CONDITION=no_trace BASE_URL=http://127.0.0.1:8050/v1 bash scripts/drivers/viki_replay_cells.sh")
    w("EXPERIMENT=rq3 MODEL=30B CONDITION=no_order BASE_URL=http://127.0.0.1:8062/v1 bash scripts/drivers/viki_replay_cells.sh")
    w("# summaries, then this README")
    w("python scripts/export_paper_viki_results.py")
    w("python scripts/write_paper_viki_readme.py")
    w("```\n")
    w("Every run directory has a `run.json` (run_id, times, model, endpoint, library path and hash, command, "
      "expected/produced n, exit status, endpoint probes before/after, resume attempts with row-file hashes).\n")
    w("## Not used\n")
    w("`VIKI_L2_PARTNR_结果_0908.pptx` and the 4-skill library, v2 libraries and v2 ablations, the comp_cd half memory, "
      "no-think (`*nt`) cells, and the stale 56-cell no_trace run. No missing row is filled with 0, and no cell is copied "
      "from another split or arm.\n")

    readme = PAPER / "README.md"
    readme.write_text("\n".join(out) + "\n")
    print("wrote", readme, "sha256", sha(readme))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
